name: Daily Upload
on:
  schedule:
    # Every Day At 08:00 JST
    - cron: '0 23 * * *'
  workflow_dispatch:
jobs:
  daily-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # npm install 後、一部ファイルはビルドしておく (アップロードするかどうかは後で特定する)
      - name: Setup npm
        run : |
          npm install
          npm run clear-dist
          npm run build-feeds
          npm run build-sitemap
      # 最終更新日が今日のファイルをビルドしてアップロードする
      - name: Detect And Upload
        run : |
          node ./.github/workflows/daily-upload.js
        env :
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
