name: FTP Upload
on:
  push:
    branches: 
      - master
jobs:
  ftp-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://s21.xrea.com
          ftp-username: neo
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: docs/
          git-ftp-args: --remote-root public_html/ --insecure
